[package]
name = "min-rust-os"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# Abort on panic instead of stack unwinding.
[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
